### ISSUE TITLE
Functions with numbers in equations

### ISSUE THREAD

**Issue by HUISUN24** [amkrajewski/TDB-Highlighter#1]
Functions have numbers within names are not highlighted

**Comment by amr8004** [comment]
+1

**Comment by amkrajewski** [comment]
Thanks for the feedback @HUISUN24 @amr8004 ! All TDBs from TDBDB I looked at had LETTERS# formatting without numbers, but it seems that [ESPEI](https://espei.org) likes to include numbers in them. I will address that soon!

**Comment by amkrajewski** [comment]
Behavior has been adjusted in Release v1.2.0. Enjoy!
