### ISSUE TITLE
[Feature request]Highlight the 80 letters limitations 

### ISSUE THREAD

**Issue by HUISUN24** [amkrajewski/TDB-Highlighter#2]
Highlight the 80 letters limitations

**Comment by amkrajewski** [comment]
Best to my knowledge, this only affects ThermoCalc software and not, e.g., pycalphad, so it doesn't seem like a necessary addition. Especially considering that you can quickly set this in VS Code manually by adding `"editor.rulers": [80]` to your `settings.json` user configuration file.

**Comment by amkrajewski** [comment]
I will mention it in the README though

**Comment by HUISUN24** [comment]
Thanks! Adam
