### ISSUE TITLE
VSCODE Dark mode default coloration bad

### ISSUE THREAD

**Issue by amr8004** [amkrajewski/TDB-Highlighter#5]
Parameter, phase name, element default coloration are defaulting to almost the same color defeating the purpose of differentiating. Consider changing phase name color in this theme

**Comment by amkrajewski** [comment]
Hi @amr8004! The root cause is that Modern Dark is explicitly defining "markup.bold" and "markup.heading"(corresponding to elements and phases, respectively) as following the exact same rendering style. To be precise:

```json
{
	"scope": "markup.bold",
	"settings": {
		"foreground": "#569CD6",
		"fontStyle": "bold"
	}
},
{
	"scope": "markup.heading",
	"settings": {
		"foreground": "#569CD6",
		"fontStyle": "bold"
	}
}
```

I will see what I can do about it, but for now I suggest you try one of other dark themes.

**Comment by amkrajewski** [comment]
After investigating, it seems like this behavior is not possible to adjust on the lexer (our) side, as there is no alternative combination of bold and color in the theme. However, you can quickly customize the theme yourself:

1. Open `settings.json`, for instance by `Ctrl`+`Shift`+`P` to bring up the command menu and typing `settings`
2. Add the following code block to it, to "steal" markup.heading formatting from Monokai theme.

```json
"editor.tokenColorCustomizations": {
   "[Default Dark Modern]": {
      "textMateRules": [
      {
         "scope": "markup.heading",
         "settings": {
             "foreground": "#D0B344"
         }
      }
      ]
   }
},
```

3. Done!

**Comment by amkrajewski** [comment]
<img width="534" alt="Screenshot 2023-11-07 at 14 01 14" src="https://github.com/amkrajewski/TDB-Highlighter/assets/54290107/9b327048-e7ba-4c22-9d7b-162aa26223f9">

**Comment by amkrajewski** [comment]
Current (V1.3.2) README in the root directory addresses this issue through instructions similar to the above ones.
