### ISSUE TITLE
Feature Request - Availability for JetBrains Products

### ISSUE THREAD

**Issue by ChRen95** [amkrajewski/TDB-Highlighter#6]
Hi, 
I wanted to ask if your thinking about making this plugin available for Jetbrains (e.g. PyCharm) products in the near future?

**Comment by amkrajewski** [comment]
Hi @ChRen95 ! Thank you for this great suggestion! I have verified the compatibility of `TDB Highlighter`'s source code with PyCharm / JetBrains and added some straightforward installation instructions to `README`. Please let me know if it works well for you :)

**Comment by amkrajewski** [comment]
Hi @ChRen95 did you have a chance to test everything with JetBrains?

**Comment by ChRen95** [comment]
> Hi @ChRen95 did you have a chance to test everything with JetBrains?

Yes, but unfortunately it doesn't work. To be more precise, I can't load it via TextMate

**Comment by amkrajewski** [comment]
@ChRen95 Could you elaborate on which JetBrains software you are using?

In my **PyCharm 2024.2.1 (Professional Edition)** (from August 29, 2024) I can get it to work without issues by:

1. Downloading and unzipping `TDB-Highlighter` in my `Documents` directory.
2. Going to `Settings.. > Editor > TextMate Bundles`.
3. Clicking on the `+`, navigating to the root directory of the unzipped `TDB-Highlighter` (see below) and clicking `Open`.
  <img width="300" alt="Screenshot" src="https://github.com/user-attachments/assets/6e2130b0-dac9-4129-8bb1-ae2326c1b3bd">
  
4. The all-lowercase `tdb-highlighter` should show up on the bundles list.
5. After around 30s or so, both `tdb` and `TDB` extensions should be correctly recognized:
  <img width="1728" alt="Screenshot 2024-10-23 at 03 43 40" src="https://github.com/user-attachments/assets/c612ff14-8532-4c93-b954-7f9e9dcfca5f">
  
6. (optional) You can also adjust the color theme under `Settings.. > Editor > Appearance` to tune it to your liking. Numerous themes can be installed from the plugin store, too. Below is the light `GitHub` theme.
  <img width="1728" alt="Screenshot 2024-10-23 at 03 42 32" src="https://github.com/user-attachments/assets/58ff2b5d-6dae-4599-9784-99c6195ab44c">

**Comment by ChRen95** [comment]
So it seems that during cloning if the repository it got damaged, maybe a faulty WiFi connection.
Nevertheless, it works as expected. Thanks.

**Comment by amkrajewski** [comment]
@ChRen95 No problem! I'm glad it worked. I will close the issue as completed.
